### ISSUE TITLE
Add validator to make sure input file is gzip-ed.

### ISSUE THREAD

**Issue by soichih** [brain-life/validator-neuro-anat#1]
I just found that, mrinfo opens t1.nii.gz that is not actually gzip-ed as a valid t1.nii - failing to validate for the file format. 

I should add a check to make sure that the input file is actually gzip-ed.

**Comment by aarya22** [comment]
Would this be solved if we switched to nibabel instead of mrinfo?

**Comment by soichih** [comment]
Probably. https://github.com/brain-life/validator-neuro-anat/issues/2

Output from mrinfo is different depending on mrtrix version, so we shouldn't be parsing mrinfo output. Using nibabel seems to be a much better solution. I am not sure if nibabel can check to see if input file is gzip or not, however.

**Comment by aarya22** [comment]
We could possibly check the magic number for gzip files. Can't remember off the top of my head or how to do that in Python.

**Comment by soichih** [comment]
It looks like `nibabel.load()` can be used to detect a case where input file is named ".nii.gz" but it's actually not compressed. 

I've created an uncompressed nifti (test.nii) and renamed it to "fake.nii.gz" without compressing it.

```
>>> img = nibabel.load("fake.nii.gz")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hayashis/.local/lib/python2.7/site-packages/nibabel/loadsave.py", line 48, in load
    filename)
nibabel.filebasedimages.ImageFileError: Cannot work out file type of "fake.nii.gz"

```

So we can put try/catch around this and detect for this error case.

**Comment by aarya22** [comment]
Makes sense. I'll make a PR shortly. Have you tested this w/nibabel on BL yet?

**Comment by soichih** [comment]
Yes, I've tested it and it works on BL. I had to make a few changes though.

**Comment by aarya22** [comment]
Would it be necessary to write another try/catch here? In the validate_anat method we already try to load with nibabel on line 42. If it is like fake.nii.gz, wouldn't that trigger the Exception anyway? In that case there would be no reason to write another try/catch to check if the file is compressed.

**Comment by soichih** [comment]
Yes, you are right. We don't need another try/catch. I think we are all set!
